name: Build and deploy MERN app to Azure Web App - knowledegify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build backend
      - name: Install dependencies and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present
          cd ..
        env:
          CI: false

      # Build frontend
      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          npm run test --if-present
          cd ..
        env:
          CI: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: mern-app
          path: . # or specify the folders you need to deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mern-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_11D72AB72C114CFEB251DFF12FA0338D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C91D9801998B4B679406ADB4285422D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_23AA122EA1A748CD910E7588F62C2AD6 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-backend
        with:
          app-name: 'backend-app-name' # replace with your backend app name
          slot-name: 'Production'
          package: ./backend

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-frontend
        with:
          app-name: 'frontend-app-name' # replace with your frontend app name
          slot-name: 'Production'
          package: ./frontend/build
